Backend/books_app/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView,
    VisitorDetailsView,
    VisitorUpdateView,
    MyLogoutView,
    BookListView,
    BookDetailsView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    CommentCreateView,
    RatingCreateView,
    SearchResultsView,
    BookViewSet,
    AuthorViewSet,
)

app_name = "books_app"

router = DefaultRouter()
router.register("books", BookViewSet)
router.register("authors", AuthorViewSet)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='books_app/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('users/<int:pk>/', VisitorDetailsView.as_view(), name='visitor_details'),
    path('users/<int:pk>/update/', VisitorUpdateView.as_view(), name='visitor_update'),
    path('', BookListView.as_view(), name='books_list'),
    path('<int:pk>/', BookDetailsView.as_view(), name='book_details'),
    path('create/', BookCreateView.as_view(), name='book_add'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
    path('<int:pk>/comments/', CommentCreateView.as_view(), name='comment_create'),
    path('rating/', RatingCreateView.as_view(), name='rating'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/books_app/forms.py
from django import forms
from books_app.models import Author, Visitor, Book, Comment


class MultipleFileInput(forms.ClearableFileInput):
    '''Класс, добавляющий возможность подгружать несколько файлов за один раз'''
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    '''Класс поля, добавляющий несколько файлов за один раз'''
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class BookWithFileForm(forms.Form):
    ''' Класс формы, для добавления книги с несколькими изображениями'''
    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

    name = forms.CharField(label='Название книги', max_length=100)
    author = forms.ModelChoiceField(queryset=Author.objects.all(), label='Автор')
    description = forms.CharField(
        label='Описание книги',
        widget=forms.Textarea(),
    )
    year = forms.DecimalField(label='Год издания', min_value=1, max_value=2050)
    images = MultipleFileField(label='Обложка и фото', required=False)


class BookUpdateForm(forms.ModelForm):
    """
    Форма обновления книги на сайте
    """
    class Meta:
        model = Book
        fields = ['name', 'author', 'year', 'description',]

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

class VisitorUpdateForm(forms.ModelForm):
    """
    Форма обновления данных пользователя
    """
    class Meta:
        model = Visitor
        fields = ('name', 'surname', 'bio')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы обновления
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class CommentCreateForm(forms.ModelForm):
    """
    Форма добавления комментариев к книге
    """
    parent = forms.IntegerField(widget=forms.HiddenInput, required=False)
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'cols': 30, 'rows': 5, 'placeholder': 'Комментарий', 'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('comment',)

Backend/books_app/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView
from rest_framework.viewsets import ModelViewSet
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from books_app.forms import BookWithFileForm, VisitorUpdateForm, BookUpdateForm, CommentCreateForm
from books_app.models import Author, Book, Visitor, Images, Comment, BookRate
from books_app.serializers import AuthorSerializer, BookSerializer
from extra_views import UpdateWithInlinesView, InlineFormSetFactory
from django.db.models import Q


class RegisterView(CreateView):
    '''
    Класс для регистрации пользователей с автозаходом на сайт
    '''
    form_class = UserCreationForm
    template_name = 'books_app/register.html'
    success_url = reverse_lazy('books_app:books_list')
    def form_valid(self, form):
        response = super().form_valid(form)
        Visitor.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


class VisitorDetailsView(DetailView):
    '''
    Класс для детальной информации о пользователе
    '''
    template_name = 'books_app/visitor_details.html'
    model = Visitor
    context_object_name = 'visitor'
    queryset = model.objects.all().select_related('user')


class VisitorUpdateView(UserPassesTestMixin, UpdateView):
    '''
    Класс для изменения информации пользователя
    '''
    def test_func(self):
        return self.request.user == self.get_object().user

    model = Visitor
    form_class = VisitorUpdateForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'books_app:visitor_details',
            kwargs={'pk': self.object.pk}
        )


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('books_app:login')


class BookDetailsView(DetailView):
    '''
    Класс для детальной информации о книге
    '''
    model = Book
    template_name = 'books_app/book_details.html'
    context_object_name = 'book'
    queryset = model.custom.detail()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['images'] = Images.objects.filter(book=self.object.pk)
        context['form'] = CommentCreateForm
        return context


class BookListView(ListView):
    '''
    Класс для вывода списка книг по 3шт на странице
    '''
    template_name = 'books_app/books_list.html'
    context_object_name = 'object_list'
    model = Book
    queryset = Book.custom.all()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        return context


class BookCreateView(LoginRequiredMixin, View):
    '''
    Класс для создания книги
    '''
    def get(self, request: HttpRequest) -> HttpResponse:
        form = BookWithFileForm()
        context = {"form": form}
        return render(request, 'books_app/book_add.html', context=context)

    def post(self, request: HttpRequest):
        form = BookWithFileForm(request.POST, request.FILES)
        if form.is_valid():
            author = Author.objects.get(pk=request.POST["author"])
            book = Book.custom.create(
                name=request.POST["name"],
                author=author,
                description=request.POST["description"],
                year=request.POST["year"],
            )
            book.save()

            images = request.FILES.getlist("images")
            for image in images:
                added_photo = Images.objects.create(image=image, book=book)
                added_photo.save()

            url = reverse('books_app:books_list')
            return redirect(url)


class ImageInline(InlineFormSetFactory):
    '''
    Класс, для создания экземпляра изображения, для присоединения к экземпляру книги
    '''
    model = Images
    fields = ['image',]
    factory_kwargs = {"extra": 1, 'can_delete': False}

class BookUpdateView(LoginRequiredMixin, UpdateWithInlinesView):
    '''
    Класс для редактирования данных о книге
    '''
    model = Book
    form_class = BookUpdateForm
    inlines = [ImageInline]
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'books_app:book_details',
            kwargs={'pk': self.object.pk}
        )


class BookDeleteView(LoginRequiredMixin, DeleteView):
    '''
    Класс для удаления книги
    '''
    model = Book
    success_url = reverse_lazy('books_app:books_list')
    context_object_name = 'book'
    template_name = 'books_app/book_delete.html'


class CommentCreateView(LoginRequiredMixin, CreateView):
    '''
    Класс, для создания древовидный коментариев
    '''
    model = Comment
    form_class = CommentCreateForm

    def is_ajax(self):
        return self.request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    def form_invalid(self, form):
        if self.is_ajax():
            return JsonResponse({'error': form.errors}, status=400)
        return super().form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.book_id = self.kwargs.get('pk')
        comment.visitor = Visitor.objects.get(user_id=self.request.user.id)
        comment.parent_id = form.cleaned_data.get('parent')
        comment.save()

        if self.is_ajax():
            return JsonResponse({
                'is_child': comment.is_child_node(),
                'id': comment.id,
                'visitor': comment.visitor.name,
                'parent_id': comment.parent_id,
                'published_at': comment.published_at.strftime('%Y-%b-%d %H:%M:%S'),
                'comment': comment.comment,
            }, status=200)

        return redirect(comment.book.get_success_url())

    def handle_no_permission(self):
        return JsonResponse({'error': 'Необходимо авторизоваться для добавления комментариев'}, status=400)


class RatingCreateView(LoginRequiredMixin, View):
    '''
    Класс для выставления оценки для книги, с отрисовкой результата на странице.
    Если повторно выбрать эту оценку - она удалится, если выбрать другую - она изменится на новое значение.
    '''
    model = BookRate
    def post(self, request, *args, **kwargs):
        book_id = request.POST.get('book_id')
        rate = int(request.POST.get('rate'))
        visitor = Visitor.objects.get(user_id=self.request.user.id)

        rating, created = self.model.objects.get_or_create(
            book_id=book_id,
            visitor=visitor,
            defaults={'rate': rate},
        )

        if not created:
            if rating.rate == rate:
                rating.delete()
                return JsonResponse({'status': 'deleted',
                                     'rating_sum': rating.book.get_sum_rating(),
                                     })
            else:
                rating.rate = rate
                rating.visitor = visitor
                rating.save()
                return JsonResponse({'status': 'updated',
                                     'rating_sum': rating.book.get_sum_rating(),
                                     })
        return JsonResponse({'status': 'created',
                             'rating_sum': rating.book.get_sum_rating(),
                             })


class SearchResultsView(ListView):
    '''
    Класс для поиска экземпляров книг по полям "Название" и "Автор"
    '''
    model = Book
    template_name = 'books_app/books_list.html'

    def get_queryset(self):
        query = self.request.GET.get('do')
        object_list = Book.custom.filter(
            Q(name__icontains=query) |
            Q(author__name__icontains=query) |
            Q(author__surname__icontains=query)
        )
        return object_list


class BookViewSet(ModelViewSet):
    '''
    Класс для создания API по книгам с различными фильтрами и поисками
    '''
    serializer_class = BookSerializer
    queryset = Book.custom.all()

    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter
    ]
    search_fields = ["name", "author__name", "author__surname", "year", "description"]
    filterset_fields = ["name", "author", "year", "description"]
    ordering_fields = ["name", "author__name", "author__surname", "year"]

class AuthorViewSet(ModelViewSet):
    '''
    Класс для создания API по авторам с различными фильтрами и поисками
    '''
    serializer_class = AuthorSerializer
    queryset = Author.objects.all()

    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter
    ]
    search_fields = ["name", "surname", "year_of_birth", "description"]
    filterset_fields = ["name", "surname", "year_of_birth", "description"]
    ordering_fields = ["name", "surname", "year_of_birth"]

Backend/books_app/templates/books_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>
        {{ title }}
        {% block title %}

        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
</head>
<body>

<div class="container">
    {% include 'header.html' %}
    <div class="row">
        <div class="col-8">
        {% block body %}

        {% endblock %}
        {% include 'pagination.html' %}
        </div>
    </div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'custom/js/backend.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

Backend/books_app/templates/books_app/book_add.html
{% extends 'books_app/base.html' %}

{% block title %}
    Add a new book
{% endblock %}

{% block body %}
    <h1>Добавить новую книгу</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить</button>
            <a href="{% url 'books_app:books_list' %}" class="btn btn-primary">Вернуться с списку книг</a>
        </form>
    </div>
{% endblock %}

Backend/books_app/templates/books_app/book_delete.html
{% extends 'books_app/base.html' %}

{% block body %}
<div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Удаление книги</h4>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="alert alert-warning" role="alert">
                <i class="fas fa-info-circle"></i> Вы собираетесь удалить книгу: <strong>{{ book.name }}</strong>, вы подтверждаете свое действие?
            </div>
            <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Удалить книгу</button>
                <a href="{% url 'books_app:book_details' pk=object.pk %}" class="btn btn-primary">Отменить удаление</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Backend/books_app/templates/books_app/book_details.html
{% extends 'books_app/base.html' %}
{% load mptt_tags static %}

{% block title %}
    Книга #{{ book.name }}.
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'books_app:book_update' pk=book.pk %}" class="btn btn-primary">Редактировать карточку</a>
        <a href="{% url 'books_app:book_delete' pk=book.pk %}" class="btn btn-primary">Удалить книгу</a>
        <a href="{% url 'books_app:books_list' %}" class="btn btn-primary">Обратно к списку книг</a>
    </div>

    <div class="card mb-3">
	<div class="row">
		<div class="col-4">
            {% if images %}
            {% for image in images %}
                <div>
                    <img src="{{ image.image.url }}" class="card-img-top" alt="{{ book.name }}">
                </div>
            {% endfor %}
            {% endif %}
		</div>

		<div class="col-8">
			<div class="card-body">
				<h5>{{ book.name }}</h5>
				<p class="card-text">{{ book.description }}</p>
				Написал: {{ book.author }} / <small>{{ book.year }}</small>
			</div>
            <div class="rating-buttons">
                <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="1">Очень плохо</button>
                <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="2">Плохо</button>
                <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="3">Средне</button>
                <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="4">Хорошо</button>
                <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="5">Отлично</button>
                <button class="btn btn-sm btn-secondary">Рейтинг книги=</button>
                <button class="btn btn-sm btn-success rating-sum">{{ book.get_sum_rating }}</button>
            </div>
		</div>
	</div>
    </div>
    <div class="card border-0">
	<div class="card-body">
		<h5 class="card-title">
			Комментарии
		</h5>
		{% include 'comments_list.html' %}
	</div>
    </div>
{% endblock %}

{% block script %}
<script src="{% static 'custom/js/ratings.js' %}"></script>
{% endblock%}

Backend/books_app/templates/books_app/book_update_form.html
{% extends 'books_app/base.html' %}

{% block title %}
    Изменение информации
{% endblock %}

{% block body %}
    <div class="card mb-3 border-0 nth-shadow">
    <div class="card-body">
        <div class="card-title nth-card-title">
            <h4>Изменить данные по книге: {{ book.name }}</h4>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
                {% for formset in inlines %}
                    <table>{{ formset }}</table>
                {% endfor %}
            <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark">Сохранить изменения</button>
                <a href="{% url 'books_app:book_details' pk=object.pk %}" class="btn btn-primary">Вернуться к книге</a>
            </div>
        </form>
    </div>
    </div>
{% endblock %}

Backend/books_app/templates/books_app/books_list.html
{% extends 'books_app/base.html' %}
{% load static %}

{% block body %}
    <div>
       <a href="{% url 'books_app:book_add' %}" class="btn btn-primary">Добавить новую книгу</a>
    </div>
    <h1>Книги:</h1>
    {% if object_list %}
        <div>
            {% for book in object_list.all %}
                <div>
                    <p><a href="{% url 'books_app:book_details' pk=book.pk %}" class="btn btn-secondary">Название: {{ book.name }}</a></p>
                    <p>Автор: {{ book.author }}</p>
                    <p>Дата издания: {{ book.year }}</p>
                    <div class="rating-buttons">
                        <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="1">Очень плохо</button>
                        <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="2">Плохо</button>
                        <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="3">Средне</button>
                        <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="4">Хорошо</button>
                        <button class="btn btn-sm btn-secondary" data-book="{{ book.id }}" data-rate="5">Отлично</button>
                        <button class="btn btn-sm btn-secondary">Рейтинг книги=</button>
                        <button class="btn btn-sm btn-success rating-sum">{{ book.get_sum_rating }}</button>
                    </div>
                    <p>-------------------------------</p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>Нет книг в библиотеке.</h3>
    {% endif %}
{% endblock %}

{% block script %}
<script src="{% static 'custom/js/ratings.js' %}"></script>
{% endblock%}

Backend/books_app/templates/books_app/login.html
{% extends 'books_app/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Login</button>
    </form>

{% endblock %}

Backend/books_app/templates/books_app/register.html
{% extends 'books_app/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

Backend/books_app/templates/books_app/visitor_details.html
{% extends 'books_app/base.html' %}

{% block title %}
    Visitor info
{% endblock %}

{% block body %}
    <h1>Личный кабинет - {{ visitor.user }}:</h1>
    {% if visitor.user.is_authenticated %}
        <h2>Детали:</h2>
        <p>Имя: {{ visitor.name }}</p>
        <p>Фамилия: {{ visitor.surname }}</p>
        <p>О себе: {{ visitor.bio }}</p>
        <div>
        <a href="{% url 'books_app:visitor_update' pk=visitor.pk %}" class="btn btn-primary">Обновить личную информацию</a>
        <a href="{% url 'books_app:books_list' %}" class="btn btn-primary">Вернуться к списку книг</a>
        </div>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

Backend/books_app/templates/books_app/visitor_update_form.html
{% extends 'books_app/base.html' %}

{% block title %}
    Update Visitor info
{% endblock %}

{% block body %}
    <h1>Обновить личные данные {{ visitor.user }}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            <a href="{% url 'books_app:books_list' %}" class="btn btn-primary">Вернуться к списку книг</a>
            <a href="{% url 'books_app:visitor_details' pk=object.pk %}" class="btn btn-primary">Вернуться в личный кабинет</a>
        </form>
    </div>
{% endblock %}