Backend/books_app/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView,
    VisitorDetailsView,
    VisitorUpdateView,
    MyLogoutView,
    BookListView,
    BookDetailsView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
    CommentCreateView,
    RatingCreateView,
    SearchResultsView,
    BookViewSet,
    AuthorViewSet,
)

app_name = "books_app"

router = DefaultRouter()
router.register("books", BookViewSet)
router.register("authors", AuthorViewSet)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='books_app/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('users/<int:pk>/', VisitorDetailsView.as_view(), name='visitor_details'),
    path('users/<int:pk>/update/', VisitorUpdateView.as_view(), name='visitor_update'),
    path('', BookListView.as_view(), name='books_list'),
    path('<int:pk>/', BookDetailsView.as_view(), name='book_details'),
    path('create/', BookCreateView.as_view(), name='book_add'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
    path('<int:pk>/comments/', CommentCreateView.as_view(), name='comment_create'),
    path('rating/', RatingCreateView.as_view(), name='rating'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('api/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/templates/comments_list.html
{% load mptt_tags static %}
<div class="nested-comments">
{% recursetree book.comments.all %}
<ul id="comment-thread-{{ node.pk }}">
    <li class="card border-0">
        <div class="row">
            <div class="col-md-10">
                <div class="card-body">
                    <h6 class="card-title">
                        <a href="{% url 'books_app:visitor_details' pk=object.pk %}">{{ node.visitor }}</a>
                    </h6>
                    <p class="card-text">
                        {{ node.comment }}
                    </p>
                    <a class="btn btn-sm btn-dark btn-reply" href="#commentForm" data-comment-id="{{ node.pk }}" data-comment-username="{{ node.visitor }}">Ответить</a>
                    <hr/>
                    <time>{{ node.published_at }}</time>
                </div>
            </div>
        </div>
    </li>
     {% if not node.is_leaf_node %}
        {{ children }}
     {% endif %}
</ul>
{% endrecursetree %}
</div>

{% if request.user.is_authenticated %}
    <div class="card border-0">
       <div class="card-body">
          <h6 class="card-title">
             Форма добавления комментария
          </h6>
          <form method="post" action="{% url 'books_app:comment_create' book.pk %}" id="commentForm" name="commentForm" data-book-id="{{ book.pk }}">
             {% csrf_token %}
             {{ form }}
             <div class="d-grid gap-2 d-md-block mt-2">
                <button type="submit" class="btn btn-dark" id="commentSubmit">Добавить комментарий</button>
             </div>
          </form>
       </div>
    </div>
{% endif %}

{% block script %}
<script src="{% static 'custom/js/comments.js' %}"></script>
{% endblock %}

Backend/templates/header.html
<header>
    <div class="px-3 py-2 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="{% url 'books_app:books_list' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>
                Список книг
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search" method="get" action="{% url 'books_app:search' %}">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" name='do' autocomplete="off" id="search">
        </form>
        {% if user.is_superuser %}
            <h3>Вы - Администратор</h3>
            <a href="{% url 'books_app:logout' %}" type="button" class="btn btn-primary">Деавторизация</a>
        {% elif request.user.is_authenticated %}
            <a href="{% url 'books_app:visitor_details' pk=user.visitor.pk %}" type="button" class="btn btn-secondary me-2">Имя: {% firstof user.visitor.name user.username %}</a>
            <a href="{% url 'books_app:logout' %}" type="button" class="btn btn-primary">Деавторизация</a>
        {% else %}
            <div class="text-end">
                <a href="{% url 'books_app:login' %}" type="button" class="btn btn-light text-dark me-2">Авторизация</a>
                <a href="{% url 'books_app:register' %}" type="button" class="btn btn-primary">Регистрация</a>
            </div>
        {% endif %}

      </div>
    </div>
  </header>

Backend/templates/pagination.html
{% if is_paginated %}
    {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
            {{page_number}}
        {% else %}
            <a href="?page={{ page_number }}" class="{% if page_number == page_obj.number %}current{% endif %}">
                {{page_number}}
            </a>
        {% endif %}
    {% endfor %}
{%endif%}